### ISSUE TITLE
InfiniteListView is null onCreate

### ISSUE THREAD

**Issue by ipepe** [ugurcany/InfiniteListView#1]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.izmyr.views.InfiniteListView.init(com.izmyr.views.InfiniteListAdapter, android.view.View)' on a null object reference

**Comment by ipepe** [comment]
My whole main_activity is null... Is this correct? Im quite new to android programming...

**Comment by ipepe** [comment]
You could add Gitter chat to Your repo

**Comment by ugurcany** [comment]
Have you inflated the InfiniteListView before `init`ializing it? You need to do so by using `findViewById()` method, or using `ButterKnife` library as I did in the example.

**Comment by ipepe** [comment]
I copied most of Your code into my app including ButterKnife. Does ButterKnife need explicit call to inflate? Is there a chance for that gitter?

**Comment by ugurcany** [comment]
Gitter added.
