### ISSUE TITLE
Why start loading is just a action method but endLoading is setter?

### ISSUE THREAD

**Issue by ipepe** [ugurcany/InfiniteListView#3]
Why start loading is just a action method but endLoading is setter?

**Comment by ugurcany** [comment]
There are both `startLoading` and `stopLoading` action methods. See the example and also the README file. The method `setEndOfLoading` has a different purpose. It indicates there are no more items to load. For instance, you are retrieving paged data from a server. When you consume all pages, you need to call `setEndOfLoading(true)` to tell the view that it should not try to load more when you swipe to the bottom again.

**Comment by ipepe** [comment]
shouldn't that be also action?

**Comment by ipepe** [comment]
also I would rename it to something like hasMore = false?

**Comment by ugurcany** [comment]
You can fork and rename it as you wish.

**Comment by ugurcany** [comment]
`setEndOfLoading` method name changed to `hasMore`.
